### ISSUE TITLE
Simple Naming System Endpoints

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-sdk-elixir#55]
Often multiple naming system operations are used successively.

This consists of 3 tasks:
### 1. Return additional data with response
`{:ok, pre_claim} =  AENS.preclaim(client, "name.test", some_salt)`
where `pre_claim` should include the cleartext name and salt passed to it.
Same for `claim`, `update` and `transfer`.

### 2. Optional functions headers
```
{:ok, pre_claim} =  AENS.preclaim(client, "name.test", some_salt)
{:ok, claim} = AENS.claim(pre_claim)
{:ok, update} = AENS.update(claim, 49_999, pointers, 50_000)
{:ok, transfer} = AENS.transfer(update, "ak_...")
{:ok, revoke} = AENS.revoke(update)
```
These simple functions should also be able to be used via pipes 
```
client 
  |> AENS.preclaim("name.test", some_salt) 
  |> AENS.claim() 
  |> AENS.update(49_999, pointers, 50_000)
```

### 3. Choose defaults automatically
With the salt being returned from the function call we gain the possibility to autogenerate it. Also other variables should default to their prototcol maximum, e.g. name update ttls.
```
client 
  |> AENS.preclaim("name.test") 
  |> AENS.claim() 
  |> AENS.update(pointers)
```

**Comment by thepiwo** [comment]
@d-velev @cheezus1 can this be applied to oracles and contracts as well?

**Comment by d-velev** [comment]
@thepiwo Doesn't make too much sense for oracles as you wouldn't register/query/respond in succession (and an operator wouldn't query his own oracle). Contracts are easily usable as they are at the moment (and do a lot of things "under the hood" where necessary)
