### ISSUE TITLE
Prepare a release 0.1 to hex

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-sdk-elixir#64]
## Depends on:
 - [x] https://github.com/aeternity/aepp-sdk-elixir/issues/60
 - [x] https://github.com/aeternity/aepp-sdk-elixir/issues/52
 - [x] https://github.com/aeternity/aepp-sdk-elixir/issues/46
 - [x] https://github.com/aeternity/aepp-sdk-elixir/issues/45
 - [x] https://github.com/aeternity/aepp-sdk-elixir/issues/57

## Requirements: 
- tag and release on github 0.1 (with some description)
- autogenerated docs to hex
- release 0.1 on hex that includes the autogenerate code, so that using elixir-sdk as a dependency works without generating code first
- make a CHANGELOG.md file in github with headline 0.1 and then describe the features we have in a few bulletpoints similar to this: https://github.com/aeternity/aesophia/blob/master/CHANGELOG.md

**Comment by DanielaIvanova** [comment]
Blocked by #76

**Comment by DanielaIvanova** [comment]
Will be done in #83
